# Configuration
env:
    global:
        secure: "iDPQpUx/GSiZCB04HXqy3Xr4ePsHBwTmUTMk1GclosXgsytzTEQXNT9P9Y0kdZ0nawYvWYDAjUECKstT8MXkzYuUZMulBXukxacGNOuLaabTUiqCH5BYYBV1aJQzFlm0p6PH84QNkfn1qffuCqAjv4NWvEwAv8QP9nzdxZdoo4olTbZ5ZFthfLhvhGOm8J3FFGjoL9GXgF6XkDg0G/Ij+28jZ5O9yM72Gd2C7mQBhBD8bTkW8B8uwsdf6mbqyKf9Xt6mol2+XqOxSHRXkRnnG7bkWBydW0B1sOti3Y3X2TfwI8cT83bSqBmuPzDMB7J1WfjXVJnEGbAPim2ZbQk0c95CRu7qWE3miCdy4MyYvNlP6OMoWUX7B1nUq604/f8kbfK3p+R1SoFYmo21XHfHto1sJjAhvIBZlA6T5Few81uN4tB/GnDxCnXFP/cpbvLYAHcopTmpndmbUHGP90HD4Q+issjtQAr6xK9oPrGoKZDJdKrZ2T8qiyZ/yVyKq2PQO6FZkH/IXr5OxEZN7J8XlsuwwyPKTr+8I/oxm9HgRB5ea0VOkBFJLAVYC1v/qnHHVK1NQNG1Po1ymgEnli3PH6uls1rUzOBB0mVkZfvHvRTCB0jg9PI+BCw4P3onn6aZ4DPm7d7PmLdfeNq6HKiUIGJkn+h4BWzjPr3gSNNDlBQ="
sudo: false
language: node_js

node_js:
    - "stable"

# The pre-install script
before_install:
    - npm i -g pnpm
    - pnpm i -g greenkeeper-lockfile@1

# The install script
install:
    - pnpm install

# The pre-build script
before_script:
    - greenkeeper-lockfile-update
    - pnpm run lint
    - chmod u+x ./bin/post-layout
    - chmod u+x ./bin/travis-push-update

# The build script
script:
    - ./bin/post-layout ../gh-pages

# The post-build script
after_script:
    - greenkeeper-lockfile-upload

# The commit script
after_success:
    - ./bin/travis-push-update

# Disable email notifications
notifications:
    email: false

# WHO IN THE F# (the programming language) DOESN’T SUPPORT TABS IN 2017? '	' <- tab
# P.S.: F# (the programming language) also doesn’t support tabs, and that's terrible
